name: Broken link checker

on:
  push:
  pull_request:

jobs:
  linkChecker:
    name: Check for broken links and create issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for broken links
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.4
        with:
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create issue
        if: failure() && github.event_name == 'push'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Broken link report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
